jms_serializer:
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
        separator: ''
        lower_case: false
    visitors:
        json_serialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
