doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    types:
        customerIdType: App\Infrastructure\Persistence\Doctrine\Type\CustomerIdType
        emailType: App\Infrastructure\Persistence\Doctrine\Type\EmailType
        phoneType: App\Infrastructure\Persistence\Doctrine\Type\PhoneType
        languageType: App\Infrastructure\Persistence\Doctrine\Type\LanguageType
        fullNameType: App\Infrastructure\Persistence\Doctrine\Type\FullNameType
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/../../src/Infrastructure/Persistence/Doctrine/Mapping'
                    prefix: 'App\Domain'
                    alias: App
                Shared:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/../../src/Shared/Infrastructure/Persistence/Doctrine/Mapping'
                    prefix: 'App\Shared\Domain'
                    alias: Shared

