framework:
    messenger:
        default_bus: query.bus
        buses:
            command.bus:
            query.bus:
        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Application\Command\Impl\SendNotificationCommand': async
            'App\Application\Command\Impl\BatchNotificationCommand': async
when@test:
    framework:
        messenger:
            routing:
                'App\Application\Command\Impl\SendNotificationCommand': sync
                'App\Application\Command\Impl\BatchNotificationCommand': sync
